apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tc-ceph-storageclass
  namespace: rook-ceph
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: pd-standard